# Netlify configuration file

# Redirect rule for handling dynamic release file requests
[[redirects]]
  # Match only paths ending in .zip under /releases/
  from = "/releases/*.zip"
  # Serve the releases.html file instead
  to = "/releases.html"
  # Status 200 means serve the file, not an HTTP redirect
  status = 200 